name: CI

on:
  push:            # ejecuta en cualquier push (a cualquier rama)
  pull_request:    # y en PRs (por ejemplo hacia main)

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]   # agrega "3.10", "3.12" si querés matriz
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          # Asegura pytest por las dudas
          python -m pip install pytest

      - name: Run tests
        run: |
          python -m pytest -q tests/test_ca.py tests/test_evo.py tests/test_graphs.py
